FROM debian

RUN apt update && apt install -y python3 build-essential cmake git python3-pip wget curl ninja-build libtinfo5 libyaml-dev build-essential clang bison flex libreadline-dev gawk tcl-dev libffi-dev git graphviz xdot pkg-config python3 libboost-system-dev libboost-python-dev libboost-filesystem-dev zlib1g-dev gdb bc
RUN pip3 install cmake
RUN useradd -u {UID} {UNAME}
RUN mkdir {HOME}
RUN chown {UNAME}:{UNAME} {HOME}
